databases:
  - name: library_db
    databaseName: library_db
    user: library_user

services:
  - type: web
    name: library-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn library_app.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: transaction_library_database
          property: connectionString
      - key: DEBUG
        value: True