databases:
  - name: transaction_library_database
    databaseName: transaction_library_database
    user: transaction_library_database_user

services:
  - type: web
    name: library-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn library_app.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: transaction_library_database
          property: connectionString
      - key: DEBUG
        value: True