# Generated by Django 5.1.7 on 2025-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='borrowed_date',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='userbook',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userbook',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='is_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='is_want_to_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbook',
            name='isbn_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
