# Generated by Django 5.1.7 on 2025-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'isbn_id')},
        ),
    ]
